### ISSUE TITLE
onNext & onBack listeners

### ISSUE THREAD

**Issue by kashifsulaiman** [samad324/react-native-animated-multistep#1]
Thanks for a great library, can you enhance your library with the onNext & onBack listeners with the index and name of the component in parameters.

Thanks

**Comment by samad324** [comment]
> Thanks for a great library, can you enhance your library with the onNext & onBack listeners with the index and name of the component in parameters.
> 
> Thanks

Thank you,  for the suggestion. I'll do it as soon as possible!

**Comment by samad324** [comment]
done!
