### ISSUE TITLE
undefined is not an object (evaluating '_this')

### ISSUE THREAD

**Issue by AndreaGProg** [samad324/react-native-animated-multistep#13]
Hi,
I have this error with React Native 0.63:

This error is located at:
    in NavigationContainer (at App.js:65)
    in NetworkConnectivity (created by ReduxNetworkProvider)
    in ReduxNetworkProvider (created by ConnectFunction)
    in ConnectFunction (at App.js:64)
    in Provider (at App.js:63)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
2020-11-06 10:17:09.263120+0100 MyApp[53880:991079] [javascript] **TypeError: undefined is not an object (evaluating '_this')**

Can you help me please?
Thanks

<img width="395" alt="Schermata 2020-11-06 alle 10 21 43" src="https://user-images.githubusercontent.com/60134321/98349642-8e165980-201a-11eb-8554-efc75018c287.png">

**Comment by AndreaGProg** [comment]
FIX:
this:
```
export class AnimatedMultistep extends Component {
  
  constructor(props) {
    this.state = {
      currentStep: 0,
      totalSteps: 0,
      userState: props.defaultState || {},
      action: "fadeInLeft",
      animationFinished: false,
    };
  }
```
    

to:
```
class AnimatedMultistep extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      currentStep: 0,
      totalSteps: 0,
      userState: props.defaultState || {},
      action: "fadeInLeft",
      animationFinished: false,
    };
  }
```

**Comment by samad324** [comment]
Can you please make a PR for this?
