### ISSUE TITLE
How to fire the onFinish function ?

### ISSUE THREAD

**Issue by priscaure** [samad324/react-native-animated-multistep#4]
Hi @samad324  ! 

Love this multistep wizard ! 
I was just wondering how to fire the onfinish function when all the steps are filled ? 

Thank you so much :)

**Comment by samad324** [comment]
Hi @priscaure!
Thank you for using `react-native-animated-multistep`.

the `onFinish` function will call automatically when you call `onNext` on the last step!

like if there is a total of 4 steps and your current step is 4. and if you call `onNext` function then `onFinish` will call automatically.

if it will help you and clear your confusion then please close this issue! and if you have any better ideas then create a pull request with your idea! 
Thanks :)

**Comment by priscaure** [comment]
Didn't expect this to be that simple haha ! It worked, thank you so much :) 

I'm closing the issue :)

**Comment by ashleighhuskinson** [comment]
How when you press next on the last step, to navigate to another page, it is not allowing it to do so
