### ISSUE TITLE
Step components jitter when animating out/in

### ISSUE THREAD

**Issue by ZarifS** [samad324/react-native-animated-multistep#5]
Hi, thank you for making this package, it is awesome. However I am running to a issue where once the components slides down/fades down it seems like it suddenly jitters and the next component/step shows up for a second before it disappears and then slides in/fades in like it should.

You can see in the gif what i mean, it seems during the fading out the two components switch spots which ends up looking very strange and jittery.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14790505/78622790-1863c880-7854-11ea-8b31-47ee1b95b71c.gif)

The way I did it is as such:

```
export default class RegisterScreen extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      email: '',
      password: '',
    };
  }

  render() {
    return (
      <Screen>
        <AnimatedMultistep
          steps={allSteps}
          comeInOnNext="fadeInDown"
          OutOnNext="fadeOutDown"
          comeInOnBack="fadeIn"
          OutOnBack="fadeOut"
        />
      </Screen>
    );
  }
}

class StepOne extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      firstName: '',
      lastName: '',
    };
  }

  nextStep = () => {
    const { next, saveState } = this.props;
    // Save state for use in other steps
    saveState(this.state);
    // Go to next step
    next();
  };

  render() {
    return (
      <InputContainer>
        <StyledText>Whats your name?</StyledText>
        <Input
          placeholder="First name"
          value={this.state.firstName}
          onChangeText={(text) => this.setState({ firstName: text })}
        />
        <Input placeholder="Last name" onChangeText={(text) => this.setState({ lastName: text })} />
        <ButtonContainer>
          <Button title="Next" small primary onPress={this.nextStep} />
        </ButtonContainer>
      </InputContainer>
    );
  }
}

class StepTwo {} --> same as stepOne basically

const allSteps = [
  { name: 'step 1', component: StepOne },
  { name: 'step 2', component: StepTwo },
];

const Screen = styled.SafeAreaView`
  background-color: ${Colors.background};
  display: flex;
  flex: 1;
`;


```

I'm not really sure how to fix this. Any suggestions would be really appreciated!

**Comment by ZarifS** [comment]
Here is another example with the default animations on

![gif](https://user-images.githubusercontent.com/14790505/78623381-8361cf00-7855-11ea-8218-0e76ca616a12.gif)

**Comment by samad324** [comment]
Hi @ZarifS! thank you for using `react-native-animated-multistep`.
I will fix it and publish a new version.

**Comment by ZarifS** [comment]
Hi i got the most recent update but it doesn't seem to have fixed the issue. Instead now the components just animate very quickly but it doesn't change the component so it looks very strange..

![gif](https://user-images.githubusercontent.com/14790505/79299085-1f708380-7eb1-11ea-90ae-f9681f35493a.gif)

Also tried adding duration but it doesn't seem to be changing anything:

```
        <AnimatedMultistep
          steps={allSteps}
          comeInOnNext="bounceInUp"
          OutOnNext="bounceOutDown"
          comeInOnBack="bounceInDown"
          OutOnBack="bounceOutUp"
          duration={5000}
        />
```

**Comment by ZarifS** [comment]
Update:

After looking at the packages file i noticed you had duration set to `100`  in the render function by default:

in index.js of Package..
``` 
  render() {
    const { steps = 0, duration=100 } = this.props;
    const { currentStep, action } = this.state;
    const Step = steps[currentStep].component;
    return (
      <Animatable.View
        ref={this.handleViewRef}
        animation={action}
        onAnimationEnd={this.animationEnd}
        style={{ flex: 1 }}
        duration={duration}
      >
        <Step
          next={this.next}
          back={this.back}
          saveState={this.saveState}
          getState={this.getState}
          getCurrentStep={this.getCurrentStep}
          getTotalSteps={this.getTotalSteps}
        />
      </Animatable.View>
    );
  }
}
```

I changed duration 100 -> 1000 and it seems to make the animaiton much smoother but it seems your props from duration doesn't get set since I can't seem to pass a custom duration. 

Thats fine tho since it is working well for me at 1000 after i manually changed it :)

**Comment by samad324** [comment]
Hi @ZarifS,
I fixed this and publish a new version on NPM! if it works fine then please this issue! and if you find some other issue, feel free to open a new one!
