### ISSUE TITLE
Slide animation

### ISSUE THREAD

**Issue by shahidcodes** [samad324/react-native-animated-multistep#8]
Hi,
I am trying to use slide animation like this -
```
<AnimatedMultistep
        steps={allSteps}
        onFinish={finish}
        onBack={onBack}
        onNext={onNext}
        comeInOnNext="slideInRight"
        OutOnNext="slideOutLeft"
        comeInOnBack="slideInLeft"
        OutOnBack="slideOutRight"
      />
```
but the problem is there's 1s delay after current page slid out of the screen and next page starts to come.

Current Page Gone -> 1s delay -> second component start animating in

**Comment by samad324** [comment]
Hi @shahidcodes,

you can use duration prop, to change the delay of animation. default is 1000 milliseconds.
